### ISSUE TITLE
EveryMinuteScheduler runs every second

### ISSUE THREAD

**Issue by vcoolish** [InsanusMokrassar/krontab#106]
Maybe I misuse it? There is only second scheduling examples.
I try to do EveryMinuteScheduler.doInfinity { println("ok") } 
it prints every second

**Comment by InsanusMokrassar** [comment]
> Maybe I misuse it? There is only second scheduling examples. I try to do EveryMinuteScheduler.doInfinity { println("ok") } it prints every second

Hello, thank you. Could you make PR with the test which will represent this problem?

**Comment by vcoolish** [comment]
thank you for quick fix!

**Comment by vcoolish** [comment]
but it didn't publish the build

**Comment by InsanusMokrassar** [comment]
> but it didn't publish the build

Glad to help :) it will be published in maven central in couple of hours

**Comment by rkokhatskyi** [comment]
Please have a look at #107, I found that EveryMinuteScheduler still runs every second with the latest version
