### ISSUE TITLE
Availability as WasmJS-Library

### ISSUE THREAD

**Issue by pheerai** [InsanusMokrassar/krontab#137]
Hi,
I'm currently trying to work with this library to replace `timer` from Kotlin/JVM, but it seems as if there's no variant for Kotlin/WasmJS available.
Would it be possible to release an (experimental) Kotlin/WasmJS-release, if that's not too much work?

**Comment by InsanusMokrassar** [comment]
Hi, looks like I have fixed missing of this target :) I hope it will work well for you after release
