### ISSUE TITLE
Weird execution of examples

### ISSUE THREAD

**Issue by NyCodeGHG** [InsanusMokrassar/krontab#22]
I don't think this is the expected behaviour

![Peek 2021-09-23 13-35](https://user-images.githubusercontent.com/37078297/134500305-f2297417-836c-4cfe-a97b-ad1fb12c49af.gif)

**Comment by InsanusMokrassar** [comment]
Thanks for your issue, I will investigate it. Could you please publish sample somewhere like gist / kotlin playground/ pastebin?

**Comment by NyCodeGHG** [comment]
https://gist.github.com/NyCodeGHG/0f662dee584d39a29d1de4264da45424

**Comment by InsanusMokrassar** [comment]
Hello, @NyCodeGHG , could you send info about your environment? I mean version of library, kotlin, coroutines and other information which could help to fix it

**Comment by NyCodeGHG** [comment]
![image](https://user-images.githubusercontent.com/37078297/134767323-c671d533-a6fb-4d50-87f0-0959977425aa.png)

I tested a bit and I noticed that the bug is only present on Linux. I was able to reproduce it in Ubuntu WSL, but it's working fine on Windows.

**Comment by InsanusMokrassar** [comment]
I suppose I found the issue and I plan to fix itbin future release. Problem is related to the fact, that your block has been executed too fast and the check of time has happened too early.

**Comment by NyCodeGHG** [comment]
Thank you for the quick response and fix

**Comment by InsanusMokrassar** [comment]
> Thank you for the quick response and fix

Thank you for your issue too
