### ISSUE TITLE
Make Kron Scheduler DSL more flexible

### ISSUE THREAD

**Issue by kfh** [InsanusMokrassar/krontab#30]
First of all, still enjoying this little library :)

So, i prefer using the _builder DSL_ for creating schedules due to type safety and verboseness. Ie when building a time zone aware scheduler that should run a job every 5 minutes i would use something like this:

```

val scheduler = buildSchedule(0) {
            minutes {
                0 every 5
            }
        }

```

And if i run this like the following: 

`scheduler.asFlow().collect { ... }` 

That gives me a timeline of all the seconds on the 5th minute since this is a _minute scheduler_ and makes my job run every second on the 5th minute. Not exactly what i want. And yes, i know i can use the schedule which takes a string cron expression as argument instead to control the data and give me exactly one DateTimeZone back. But as stated, i want to use the DSL builder.

So, i think in most cases you want to trigger your job only once with most schedulers so we need to control seconds, minutes and so on when we use schedulers other than the seconds scheduler. What i've ended up doing is writing a little extension functions like the following:

```

  @FlowPreview
  private fun KronScheduler.asSingleTzFlow(seconds: Int = 0): Flow<DateTimeTz> = channelFlow {
      doInfinityTz {
          send(it)
      }
  }
      .filter { it.seconds == seconds }

```

Which solves this problem without a lot of fuzz :) But i was thinking that maybe this is a function that should be included in your library. I think it would be great if we had api functions for all the other schedulers than seconds like this so we can override the seconds, minutes and so forth properties in an easy and concise way.

Thoughts ?

**Comment by InsanusMokrassar** [comment]
Hello and thank you for your issue :) do I correctly understand that you want some way where we will trigger datetime collecting only for the times we set up in builder? For example, if you set `minutes { every(5) }`, you want to get trigger each five minutes at 0 seconds. Do I correctly understand your idea?
