### ISSUE TITLE
doOnce on set intervals does not work as expected

### ISSUE THREAD

**Issue by Martmists-GH** [InsanusMokrassar/krontab#96]
Example code:

```kotlin
doOnce("* 0/2 * * *") {
    println("Hello World!")
}
```

Expected behavior: prints "Hello World!" once every other minute.

Actial Behavior: Seems to trigger only once or twice

**Comment by InsanusMokrassar** [comment]
> Example code:
> 
> ```kotlin
> doOnce("* 0/2 * * *") {
>     println("Hello World!")
> }
> ```
> 
> Expected behavior: prints "Hello World!" once every other minute.
> 
> Actial Behavior: Seems to trigger only once or twice

Hi :) `doOnce` functions trigger callback only once (if twice - it is error, please, feel free to report that case). You may read [docs](https://docs.inmo.dev/krontab/index.html) to get more info about available ways to trigger actions by krontab string :)

**Comment by Martmists-GH** [comment]
Hmm, but doWhile and doInfinity trigger every second with this configuration, even though it should only be once a minute.

**Comment by InsanusMokrassar** [comment]
> That'd make sense, but doWhile and doInfinity trigger every second with this configuration, even though it should only be once every 2 minutes to my knowledge, so I'm unsure what to do here to get the desired result.

Look [here](https://insanusmokrassar.github.io/KrontabPredictor/?krontab=*%200%2F2%20*%20*%20*) for your krontab settings explanation

**Comment by Martmists-GH** [comment]
oh, so it's different from regular cron format in that regard?

**Comment by InsanusMokrassar** [comment]
> oh, so it's different from regular cron format in that regard?

Yes, all the differences described in docs
